from django.core.management.base import BaseCommand
from menu.models import Category, Product

# (name, price, is_veg, subcategory)
MENU = [
    ("TEA", [
        ("Milk Tea", "30", True, ""),
        ("Black Tea", "20", True, ""),
        ("Lemon Tea", "25", True, ""),
        ("Hot Lemon with Honey & Ginger", "150", True, ""),
        ("Black Coffee", "70", True, ""),
        ("Milk Coffee", "100", True, ""),
        ("Green Tea", "50", True, ""),
        ("Lemon Green Tea", "60", True, ""),
    ]),
    ("COLD DRINKS", [
        ("Pepsi", "70", True, ""),
        ("Mirinda", "70", True, ""),
        ("7 Up", "70", True, ""),
        ("Mountain Dew", "70", True, ""),
        ("Slice", "70", True, ""),
        ("Red Bull Nep.", "130", True, ""),
        ("Red Bull Aus.", "250", True, ""),
        ("Xtreme", "150", True, ""),
        ("Real Juice (per glass)", "130", True, ""),
    ]),
    ("CHOWMIN", [
        ("Veg Chowmin", "110", True, ""),
        ("Chicken Chowmin", "160", False, ""),
        ("Mutton Chowmin", "200", False, ""),
        ("Egg Chowmin", "160", False, ""),
        ("Mix Non-Veg Chowmin", "220", False, ""),
        ("Pork Chowmin", "170", False, ""),
    ]),
    ("MOMO", [
        ("Chicken", "160", False, "Steam"),
        ("Pork", "170", False, "Steam"),
        ("Veg", "110", True, "Steam"),
        ("Chicken", "180", False, "Jhol"),
        ("Pork", "180", False, "Jhol"),
        ("Veg", "150", True, "Jhol"),
        ("Chicken", "190", False, "Fry"),
        ("Pork", "200", False, "Fry"),
        ("Veg", "160", True, "Fry"),
        ("Chicken", "220", False, "C' Momo"),
        ("Pork", "220", False, "C' Momo"),
        ("Veg", "180", True, "C' Momo"),
        ("Balmeky Momo", "170", False, "Special"),
        ("Kothey Momo", "160", False, "Special"),
    ]),
    ("THUKPA", [
        ("Chicken Thukpa", "170", False, ""),
        ("Mutton Thukpa", "200", False, ""),
        ("Egg Thukpa", "150", False, ""),
        ("Non-Veg Mix Thukpa", "280", False, ""),
        ("Veg Thukpa", "120", True, ""),
        ("Pork Thukpa", "180", False, ""),
    ]),
    ("LASSI", [
        ("Sweet Lassi (Plain)", "150", True, ""),
        ("Chocolate Lassi", "180", True, ""),
        ("Strawberry Lassi", "180", True, ""),
    ]),
    ("SALAD", [
        ("Nepali Salad", "160", True, ""),
        ("Green Salad", "160", True, ""),
    ]),
    ("VEG ITEMS", [
        ("French Fry", "160", True, ""),
        ("Chips Chilly", "200", True, ""),
        ("Veg Pakoda", "150", True, ""),
        ("Mushroom Pakoda", "200", True, ""),
        ("Union Pakoda", "180", True, ""),
        ("Paneer Chilly", "280", True, ""),
        ("Aalu Jeera Fry", "150", True, ""),
        ("Mustang Aalu Fry", "180", True, ""),
        ("Peanuts Sadeko", "170", True, ""),
        ("Bhatmas Sadeko", "160", True, ""),
        ("Wai Wai Sadeko", "150", True, ""),
        ("Sweet Corn Sadeko", "150", True, ""),
        ("Corn Salt and Paper", "220", True, ""),
        ("Paneer Pakoda", "270", True, ""),
        ("Plain Peanuts", "120", True, ""),
        ("Dry / Fry Papad", "120", True, ""),
        ("Masala Papad", "150", True, ""),
        ("Cheese Kurket", "330", True, ""),
        ("Wai Wai With Murai", "160", True, ""),
        ("Wai Wai Chiura with Fry Papad", "230", True, ""),
        ("Wai Wai Chiura with Fry Papad Egg", "290", False, ""),
        ("Mushroom Chilly", "280", True, ""),
    ]),
    ("BIRYANI", [
        ("Veg Biryani", "300", True, ""),
        ("Chicken Biryani", "370", False, ""),
        ("Egg Biryani", "380", False, ""),
        ("Mutton Biryani", "450", False, ""),
        ("Pork Biryani", "380", False, ""),
    ]),
    ("RICE ITEMS", [
        ("Veg Rice", "140", True, ""),
        ("Chicken Rice", "170", False, ""),
        ("Mutton Rice", "220", False, ""),
        ("Egg Rice", "180", False, ""),
        ("Mix Veg Rice", "150", True, ""),
        ("Mix Non-Veg Rice", "250", False, ""),
        ("Pork Fry Rice", "180", False, ""),
    ]),
    ("CORN DOG", [
        ("Cheese Dog", "400", True, ""),
        ("Cheese Sausage", "360", False, ""),
    ]),
    ("SANDWICH", [
        ("Chicken Sandwich", "180", False, ""),
        ("Veg Sandwich", "160", True, ""),
    ]),
    ("BURGER", [
        ("Chicken Burger", "280", False, ""),
        ("Veg Burger", "200", True, ""),
        ("Crunchy Burger", "290", False, ""),
        ("Extra Cheese", "60", True, ""),
    ]),
    ("SAUSAGE", [
        ("Sausage Fry", "220", False, ""),
        ("Sausage Chilly", "235", False, ""),
        ("Sausage Boil", "200", False, ""),
    ]),
    ("SOUP", [
        ("Non-Veg Mix Soup", "180", False, ""),
        ("Veg Soup", "110", True, ""),
        ("Chicken Soup", "150", False, ""),
        ("Mushroom Soup", "130", True, ""),
    ]),
    ("PIZZA", [
        ("Mix Veg Pizza", "400", True, ""),
        ("Mix Non-Veg Pizza", "460", False, ""),
        ("Chicken Pizza", "400", False, ""),
        ("Cheese Pizza", "410", True, ""),
        ("Mushroom Pizza", "440", True, ""),
        ("Veg Pizza", "390", True, ""),
        ("Extra Cheese", "60", True, ""),
    ]),
    ("SIZZLER", [
        ("Chicken Sizzler", "450", False, ""),
        ("Mutton Sizzler", "500", False, ""),
        ("Veg Sizzler", "350", True, ""),
        ("Pork Sizzler", "450", False, ""),
    ]),
    ("CHICKEN ITEMS", [
        ("Chicken Fry", "250", False, ""),
        ("Chicken Chilly", "270", False, ""),
        ("Chicken Nuggets", "300", False, ""),
        ("Chicken Sadeko", "230", False, ""),
        ("Chicken Popcorn", "240", False, ""),
        ("Chicken Tawa", "300", False, ""),
        ("Chicken Pakoda", "230", False, ""),
        ("Chicken Choila", "270", False, ""),
        ("Chicken Drumstick", "280", False, ""),
        ("Chicken Cheese Drumstick", "390", False, ""),
        ("Chicken Lollipop", "290", False, ""),
        ("Chicken Boil", "200", False, ""),
        ("Chicken Sekuwa", "350", False, ""),
        ("Chicken Roast", "320", False, ""),
        ("KFC Chicken", "270", False, ""),
        ("Chicken Cut Leg", "290", False, ""),
        ("Chicken Leg Fry", "290", False, ""),
        ("Lemon Chicken", "260", False, ""),
        ("Spicy Wings", "320", False, ""),
        ("Chicken Bread", "290", False, ""),
    ]),
    ("BUFF", [
        ("Buff Sukuti", "250", False, ""),
        ("Buff Sadeko", "200", False, ""),
        ("Buff Choila", "220", False, ""),
        ("Buff Sekuwa", "250", False, ""),
    ]),
    ("PORK", [
        ("Pork Fry", "230", False, ""),
        ("Pork Dameko", "260", False, ""),
        ("Pork Sadeko", "260", False, ""),
        ("Pork Sekuwa", "260", False, ""),
        ("Pork Choila", "240", False, ""),
        ("Pork Chilly", "280", False, ""),
    ]),
    ("MUTTON ITEMS", [
        ("Mutton Jhaneko Sekuwa", "450", False, ""),
        ("Mutton Dameko", "400", False, ""),
        ("Mutton Choila", "400", False, ""),
        ("Mutton Fry", "400", False, ""),
        ("Mutton Boil", "350", False, ""),
        ("Mutton Sadeko", "400", False, ""),
        ("Mutton Roast", "350", False, ""),
    ]),
    ("CHOPSUEY", [
        ("American Chopsuey Veg", "290", True, ""),
        ("American Chopsuey Non-Veg", "380", False, ""),
        ("Chinese Chopsuey Veg", "290", True, ""),
        ("Chinese Chopsuey Non-Veg", "380", False, ""),
    ]),
    ("OMLET ITEMS", [
        ("Egg Boil (2 pcs)", "100", False, ""),
        ("Egg Pakoda", "140", False, ""),
        ("Egg Poz", "130", False, ""),
        ("Egg Omlet (Special)", "200", False, ""),
        ("Plain Omlet (Normal)", "180", False, ""),
    ]),
    ("KBR KHAJA SET", [
        ("Masu Chiura", "260", False, ""),
        ("KBR Khaja Set Veg", "280", True, ""),
        ("KBR Khaja Set Chicken", "360", False, ""),
        ("KBR Khaja Set Pork", "390", False, ""),
    ]),
    ("HUKKA", [
        ("Hukka", "350", True, ""),
        ("Coal Change", "50", True, ""),
    ]),
    ("BEER", [
        ("Tuborg Big", "550", True, ""),
        ("Gorkha Strong Big", "420", True, ""),
        ("Gorkha Strong Small", "250", True, ""),
        ("Mustang Big", "390", True, ""),
        ("Mustang Small", "240", True, ""),
        ("Carlsberg Big", "N/A", True, ""),
    ]),
    ("WHISKEY", [
        ("Double Black", "380 / 760 / 11500", True, ""),
        ("Black Label", "340 / 665 / 10300", True, ""),
        ("Red Label", "275 / 540 / 8500", True, ""),
        ("Jack Daniels", "330 / 650 / 9900", True, ""),
        ("Signature Red", "135 / 260 / 3000", True, ""),
        ("Old Durbar Red", "160 / 300 / 3350", True, ""),
        ("Old Durbar Black Chemmy", "195 / 380 / 4350", True, ""),
        ("Golden Oak Small", "450", True, ""),
        ("Golden Oak Medium", "800", True, ""),
        ("Golden Oak Large", "1500", True, ""),
        ("Batla Full", "1600", True, ""),
        ("Batla Quarter", "450", True, ""),
        ("Batla Half", "800", True, ""),
        ("CB (The Classic) Full", "1600", True, ""),
        ("CB (The Classic) Quarter", "450", True, ""),
        ("CB (The Classic) Half", "800", True, ""),
    ]),
    ("RUM", [
        ("Kukhuri Rum", "110 / 210 / 2500", True, ""),
    ]),
    ("VODKA", [
        ("8848", "120 / 230 / 2550", True, ""),
    ]),
    ("APPLESIDER & WINE", [
        ("Applesider", "260", True, ""),
        ("Big Master", "950", True, ""),
        ("Proto", "2800", True, ""),
        ("Robortson", "1850", True, ""),
        ("JP Chenet", "2350", True, ""),
        ("Divine", "950", True, ""),
    ]),
]


class Command(BaseCommand):
    help = 'Seed the database with KBR menu data'

    def handle(self, *args, **kwargs):
        Product.objects.all().delete()
        Category.objects.all().delete()

        for order, (cat_name, items) in enumerate(MENU):
            cat = Category.objects.create(name=cat_name, order=order)
            for i, (name, price, is_veg, subcat) in enumerate(items):
                Product.objects.create(
                    category=cat,
                    name=name,
                    price=price,
                    is_veg=is_veg,
                    subcategory=subcat,
                    is_available=True,
                    order=i,
                )
            self.stdout.write(f'  OK: {cat_name} ({len(items)} items)')

        self.stdout.write(self.style.SUCCESS('Menu seeded successfully!'))
