"""
Utility to fetch a relevant food image URL from Pexels API.
Get your free API key at: https://www.pexels.com/api/
"""
import urllib.request
import urllib.parse
import json
import os

PEXELS_API_KEY = os.environ.get('PEXELS_API_KEY', '')

# Smart search query overrides for items whose names are ambiguous
QUERY_OVERRIDES = {
    'milk tea':             'milk tea drink',
    'black tea':            'black tea cup',
    'lemon tea':            'lemon tea glass',
    'black coffee':         'black coffee cup',
    'milk coffee':          'coffee with milk',
    'green tea':            'green tea cup',
    'lemon green tea':      'lemon green tea',
    'hot lemon with honey & ginger': 'lemon honey ginger tea',
    'pepsi':                'pepsi cola can',
    'mirinda':              'orange soda drink',
    '7 up':                 '7up soda drink',
    'mountain dew':         'mountain dew soda',
    'slice':                'mango juice drink',
    'red bull nep.':        'red bull energy drink',
    'red bull aus.':        'red bull energy drink',
    'xtreme':               'energy drink can',
    'real juice (per glass)':'fruit juice glass',
    'veg chowmin':          'vegetable chow mein noodles',
    'chicken chowmin':      'chicken chow mein noodles',
    'mutton chowmin':       'mutton noodles',
    'egg chowmin':          'egg noodles',
    'mix non-veg chowmin':  'mixed noodles',
    'pork chowmin':         'pork noodles',
    'chicken':              'chicken momo dumplings',
    'pork':                 'pork dumplings',
    'veg':                  'vegetable dumplings',
    'balmeky momo':         'fried dumplings',
    'kothey momo':          'pan fried dumplings',
    'chicken thukpa':       'chicken noodle soup',
    'mutton thukpa':        'mutton noodle soup',
    'egg thukpa':           'egg noodle soup',
    'veg thukpa':           'vegetable noodle soup',
    'pork thukpa':          'pork noodle soup',
    'non-veg mix thukpa':   'mixed noodle soup',
    'sweet lassi (plain)':  'sweet lassi yogurt drink',
    'chocolate lassi':      'chocolate lassi drink',
    'strawberry lassi':     'strawberry lassi drink',
    'nepali salad':         'fresh salad bowl',
    'green salad':          'green salad bowl',
    'french fry':           'french fries',
    'chips chilly':         'chilli chips snack',
    'veg pakoda':           'vegetable pakoda fritters',
    'mushroom pakoda':      'mushroom fritters',
    'union pakoda':         'onion pakoda fritters',
    'paneer chilly':        'paneer chilli dish',
    'aalu jeera fry':       'potato cumin fry',
    'mustang aalu fry':     'spicy potato fry',
    'peanuts sadeko':       'spiced peanuts',
    'bhatmas sadeko':       'spiced soybeans',
    'wai wai sadeko':       'spiced noodles snack',
    'sweet corn sadeko':    'spiced sweet corn',
    'corn salt and paper':  'corn salt pepper snack',
    'paneer pakoda':        'paneer fritters',
    'plain peanuts':        'roasted peanuts',
    'dry / fry papad':      'papad crispy',
    'masala papad':         'masala papad',
    'cheese kurket':        'cheese snack',
    'mushroom chilly':      'mushroom chilli stir fry',
    'veg biryani':          'vegetable biryani rice',
    'chicken biryani':      'chicken biryani',
    'egg biryani':          'egg biryani',
    'mutton biryani':       'mutton biryani',
    'pork biryani':         'pork fried rice',
    'veg rice':             'steamed vegetable rice',
    'chicken rice':         'chicken fried rice',
    'mutton rice':          'mutton rice',
    'egg rice':             'egg fried rice',
    'mix veg rice':         'mixed vegetable rice',
    'mix non-veg rice':     'mixed fried rice',
    'pork fry rice':        'pork fried rice',
    'cheese dog':           'corn dog cheese',
    'cheese sausage':       'cheese sausage',
    'chicken sandwich':     'chicken sandwich',
    'veg sandwich':         'vegetable sandwich',
    'chicken burger':       'chicken burger',
    'veg burger':           'veggie burger',
    'crunchy burger':       'crispy chicken burger',
    'extra cheese':         'melted cheese',
    'sausage fry':          'fried sausage',
    'sausage chilly':       'sausage chilli',
    'sausage boil':         'boiled sausage',
    'non-veg mix soup':     'mixed meat soup',
    'veg soup':             'vegetable soup bowl',
    'chicken soup':         'chicken soup bowl',
    'mushroom soup':        'mushroom soup bowl',
    'mix veg pizza':        'vegetable pizza',
    'mix non-veg pizza':    'meat pizza',
    'chicken pizza':        'chicken pizza',
    'cheese pizza':         'cheese pizza',
    'mushroom pizza':       'mushroom pizza',
    'veg pizza':            'vegetable pizza',
    'chicken sizzler':      'chicken sizzler plate',
    'mutton sizzler':       'mutton sizzler',
    'veg sizzler':          'vegetable sizzler',
    'pork sizzler':         'pork sizzler',
    'chicken fry':          'fried chicken',
    'chicken chilly':       'chicken chilli',
    'chicken nuggets':      'chicken nuggets',
    'chicken sadeko':       'spiced chicken',
    'chicken popcorn':      'chicken popcorn',
    'chicken tawa':         'chicken tawa',
    'chicken pakoda':       'chicken fritters',
    'chicken choila':       'chicken choila',
    'chicken drumstick':    'chicken drumstick',
    'chicken lollipop':     'chicken lollipop',
    'chicken boil':         'boiled chicken',
    'chicken sekuwa':       'chicken sekuwa grilled',
    'chicken roast':        'roast chicken',
    'kfc chicken':          'fried chicken',
    'chicken cut leg':      'chicken leg piece',
    'chicken leg fry':      'fried chicken leg',
    'lemon chicken':        'lemon chicken',
    'spicy wings':          'spicy chicken wings',
    'chicken bread':        'chicken bread roll',
    'buff sukuti':          'dried meat sukuti',
    'buff sadeko':          'spiced buff meat',
    'buff choila':          'buff choila',
    'buff sekuwa':          'grilled buff sekuwa',
    'pork fry':             'fried pork',
    'pork dameko':          'spiced pork',
    'pork sadeko':          'spiced pork',
    'pork sekuwa':          'grilled pork',
    'pork choila':          'pork choila',
    'pork chilly':          'pork chilli',
    'mutton jhaneko sekuwa':'grilled mutton sekuwa',
    'mutton dameko':        'spiced mutton',
    'mutton choila':        'mutton choila',
    'mutton fry':           'fried mutton',
    'mutton boil':          'boiled mutton',
    'mutton sadeko':        'spiced mutton',
    'mutton roast':         'mutton roast',
    'american chopsuey veg':'american chop suey vegetable',
    'american chopsuey non-veg': 'american chop suey meat',
    'chinese chopsuey veg': 'chinese chop suey vegetable',
    'chinese chopsuey non-veg': 'chinese chop suey meat',
    'egg boil (2 pcs)':     'boiled eggs',
    'egg pakoda':           'egg fritters',
    'egg poz':              'egg dish',
    'egg omlet (special)':  'omelette special',
    'plain omlet (normal)': 'plain omelette',
    'masu chiura':          'beaten rice meat',
    'kbr khaja set veg':    'nepali snack set',
    'kbr khaja set chicken':'nepali chicken snack set',
    'kbr khaja set pork':   'nepali pork snack set',
    'hukka':                'hookah shisha',
    'coal change':          'hookah coal',
    'tuborg big':           'tuborg beer bottle',
    'gorkha strong big':    'beer bottle',
    'gorkha strong small':  'beer bottle',
    'mustang big':          'beer bottle',
    'mustang small':        'beer bottle',
    'carlsberg big':        'carlsberg beer',
    'double black':         'whiskey glass',
    'black label':          'black label whiskey',
    'red label':            'red label whiskey',
    'jack daniels':         'jack daniels whiskey',
    'signature red':        'whiskey glass',
    'old durbar red':       'whiskey bottle',
    'old durbar black chemmy': 'whiskey bottle',
    'golden oak small':     'whiskey glass',
    'golden oak medium':    'whiskey bottle',
    'golden oak large':     'whiskey bottle',
    'batla full':           'whiskey bottle',
    'kukhuri rum':          'rum bottle glass',
    '8848':                 'vodka glass',
    'applesider':           'apple cider drink',
    'big master':           'wine bottle',
    'proto':                'red wine glass',
    'robortson':            'wine bottle',
    'jp chenet':            'wine glass',
    'divine':               'wine glass',
}


def get_search_query(product_name: str) -> str:
    key = product_name.lower().strip()
    return QUERY_OVERRIDES.get(key, f'{product_name} food')


def fetch_pexels_image(product_name: str) -> str:
    """Return a Pexels image URL for the given product name, or '' on failure."""
    if not PEXELS_API_KEY:
        return ''
    query = get_search_query(product_name)
    url = f'https://api.pexels.com/v1/search?query={urllib.parse.quote(query)}&per_page=1&orientation=square'
    req = urllib.request.Request(url, headers={'Authorization': PEXELS_API_KEY})
    try:
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read())
            photos = data.get('photos', [])
            if photos:
                return photos[0]['src']['medium']
    except Exception:
        pass
    return ''
